import "~/styles/globals.css";

import { type Metadata } from "next";
import { Comforter_Brush, Fondamento } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fondamento = Fondamento({
  subsets: ["latin"],
  weight: ["400", "400"],
  style: ["normal", "italic"],
  variable: "--font-fondamento",
});

const comforterBrush = Comforter_Brush({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-comforter-brush",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${fondamento.variable} ${comforterBrush.variable} font-fondamento flex min-h-screen min-w-screen flex-col items-center justify-center bg-black text-white`}
    >
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
